#!/usr/bin/env python3
"""Test Google News RSS accessibility from GitHub Actions"""
import requests, sys, re, datetime


def main():
    companies = [
        'ByteDance', 'TikTok', 'Tencent', 'Alibaba', 'JD.com', 'Kuaishou', 'Ant Group',
        'Meituan', 'Kakao', 'Naver', 'Rakuten', 'Sea Limited', 'Grab', 'Gojek',
        'VNG Group', 'Yahoo', 'Cyberagent', 'Adyen', 'Zalando', 'Allegro', 'Trendyol',
        'MercadoLibre', 'Rappi', 'Noon', 'Careem', 'Tabby', 'Kaspi.kz', 'Jumia', 'Konga',
    ]
    ok, fail = 0, []
    results = []
    for name in companies:
        url = 'https://news.google.com/rss/search?q=' + requests.utils.quote(name) + '&hl=en-US&gl=US&ceid=US:en'
        try:
            r2 = requests.get(url, timeout=15)
            if r2.status_code == 200 and '<rss' in r2.text:
                items = re.findall(r'<title>(.*?)</title>', r2.text)
                count = len(items) - 1
                line = 'OK  ' + name.ljust(15) + ' | ' + str(count) + ' titles'
                print(line)
                results.append((name, 'OK', count))
                ok += 1
            else:
                line = 'FAIL ' + name + ' | HTTP ' + str(r2.status_code)
                print(line)
                results.append((name, 'FAIL', r2.status_code))
                fail.append(name)
        except Exception as e:
            line = 'FAIL ' + name + ' | ' + type(e).__name__
            print(line)
            results.append((name, 'ERROR', str(e)))
            fail.append(name)

    print('Result: ' + str(ok) + '/' + str(len(companies)) + ' accessible from GitHub Actions')

    # Write results to file
    with open('rss_test_results.md', 'w', encoding='utf-8') as f:
        f.write('# Google News RSS Accessibility Test\n')
        f.write(f'**Date**: {datetime.datetime.now().isoformat()}\n\n')
        f.write(f'**Result**: {ok}/{len(companies)} accessible\n\n')
        f.write('| Company | Status | Details |\n')
        f.write('|---------|--------|---------|\n')
        for name, status, detail in results:
            f.write(f'| {name} | {status} | {detail} |\n')
        if fail:
            f.write(f'\n**Failed**: {", ".join(fail)}\n')
        f.write(f'\n---\nGenerated by GitHub Actions RSS Test\n')

    if fail:
        sys.exit(1)


if __name__ == '__main__':
    main()
